columns:
  name:
    type: text
    options:
      label: admin.gallery.list.name
      editable: true
  visible:
    type: boolean
    options:
      label: admin.gallery.list.visible
      editable: true
  actions:
    type: action
    options:
      label: admin.gallery.list.actions
      field_mapping: ['id']
      actions:
        edit:
          route_name: fsi_admin_crud_edit
          additional_parameters: {'element' : 'gallery'}
          parameters_field_mapping: {'id' : 'id'}